<!DOCTYPE html>
<html lang="en">
<head>
<title><?php echo $this->hiiirSettings("website_title"); ?></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/css/bootstrap/bootstrap.css" media="all" rel="stylesheet" type="text/css">
<link href="/css/bootstrap/main.css" media="all" rel="stylesheet" type="text/css">
<link href="/css/bootstrap/bootstrap-responsive.css" media="all" rel="stylesheet" type="text/css">
<style type="text/css">
  body {
    padding-top: 40px;
    padding-bottom: 40px;
    background-color: #f5f5f5;
  }

  .form-signin {
    max-width: 300px;
    padding: 19px 29px 29px;
    margin: 0 auto 20px;
    background-color: #fff;
    border: 1px solid #e5e5e5;
    -webkit-border-radius: 5px;
       -moz-border-radius: 5px;
            border-radius: 5px;
    -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
       -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
  }
  .form-signin .form-signin-heading,
  .form-signin .checkbox {
    margin-bottom: 10px;
  }
  .form-signin input[type="text"],
  .form-signin input[type="password"] {
    font-size: 16px;
    height: auto;
    margin-bottom: 15px;
    padding: 7px 9px;
  }
</style>
<!--[if lt IE 9]><script type="text/javascript" src="/js/bootstrap/html5.js"></script><![endif]-->
</head>
<body>
  <div class="container">
    <blockquote>
      <h1>OUCH!</h1>
      <h2>抱歉！您欲尋找的頁面並不存在！</h2>
    </blockquote>
  </div>
  <p class="muted">Copyright © 2013 Hiiir.Inc</p>
</body>
</html>